### ISSUE TITLE
Extend IntConversion to support byte and short and values without quotes

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#101]

**Comment by hft-team-city** [comment]
Released in Chronicle-Wire-1.16.17 (https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-1.16.17), BOM-1.16.170 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.170)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
