### ISSUE TITLE
writeText/readText doesn't work when padding is enabled.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#105]

**Comment by hft-team-city** [comment]
Released in Chronicle-Wire-1.16.19 (https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-1.16.19), BOM-1.16.201 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.201)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
