### ISSUE TITLE
Port Chronicle-Wire to C++

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Wire#106]

**Comment by RobAustin** [comment]
closing as duplicate

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.6](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.6), [BOM-2.17.72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.72)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.6](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.6), [BOM-2.17.74](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.74)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
