### ISSUE TITLE
Fix issue where newLongReference() was not being assigned correctly when calling setValue(..)

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Wire#107]

**Comment by hft-team-city** [comment]
Released in Chronicle-Wire-2.17.2 (https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.2), BOM-2.17.8 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.8)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
