### ISSUE TITLE
Sometime append(double) writes one too many digits

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#110]
This appears to be a fault in asDouble.

**Comment by RobAustin** [comment]
@peter-lawrey can this be closed, I'll close it, please reopen if you disagree

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.6](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.6), [BOM-2.17.72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.72)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.6](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.6), [BOM-2.17.74](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.74)

**Comment by RobAustin** [comment]
@peter-lawrey  As there appears to still be an issue here, I will re-open this issue.

**Comment by JerryShea** [comment]
https://github.com/OpenHFT/Chronicle-Bytes/issues/85 has fixed the test that was originally built for this issue. Do we have some more failure scenarios?

**Comment by peter-lawrey** [comment]
I don't believe so. Closing.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.25](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.25), [BOM-2.17.196](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.196)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.25](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.25), [BOM-2.17.225](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.225)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.25](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.25), [BOM-2.17.241](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.241)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
