### ISSUE TITLE
Add a LongConverter for Duration

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#113]
Like MicroTimestampLongConverter it would be useful to have a converter for Durations.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.9](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.9), [BOM-2.17.119](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.119)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.9](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.9), [BOM-2.17.196](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.196)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.9](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.9), [BOM-2.17.225](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.225)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.9](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.9), [BOM-2.17.241](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.241)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
