### ISSUE TITLE
Added code generation to fix the args[] object generation with is created via the Proxy

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Wire#115]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.12](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.12), [BOM-2.17.196](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.196)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.12](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.12), [BOM-2.17.225](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.225)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.12](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.12), [BOM-2.17.241](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.241)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
