### ISSUE TITLE
Added support for regressing the output

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#125]
When
```
-Dregress.tests=true
```
is set on the command line, existing `out.yaml` files are overwritten instead of checked.

This should be used with care and the resulting changes to the output checked before checking them in.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.25](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.25), [BOM-2.17.196](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.196)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.25](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.25), [BOM-2.17.225](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.225)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.25](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.25), [BOM-2.17.241](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.241)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
