### ISSUE TITLE
Improved deepCopy() efficiency

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#132]
deepCopy uses serialization/deserialization which is inefficient.
This will be replaced with a field by field copy in many cases.
Some cases such as arrays and collections will still delegate to serialization.

**Comment by dpisklov** [comment]
Seems to be done?

**Comment by dpisklov** [comment]
Clearly we need more test coverage around this, it's a bit worrying that we only discover this so deep down the projects stack

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.26](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.26), [BOM-2.17.196](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.196)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.26](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.26), [BOM-2.17.225](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.225)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.26](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.26), [BOM-2.17.241](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.241)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.14](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.14), [BOM-2.20.36](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.36)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
