### ISSUE TITLE
Improved handling of static methods in generated Proxy(s)

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#133]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.14](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.14), [BOM-2.20.36](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.36)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
