### ISSUE TITLE
Add support for Base40 with uppercase and digits

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#136]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.31](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.31), [BOM-2.17.196](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.196)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.31](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.31), [BOM-2.17.225](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.225)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.31](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.31), [BOM-2.17.241](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.241)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
