### ISSUE TITLE
Throw exception if user tries to use MethodReader with overloaded methods

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Wire#141]
The old behaviour (just log a warning) can be restored with `-Dchronicle.mr_overload_dont_throw=true`

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.39](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.39), [BOM-2.17.267](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.267)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
