### ISSUE TITLE
Is this bit of code accidentally commented out ?

### ISSUE THREAD

**Issue by AlexWibowoANZ** [OpenHFT/Chronicle-Wire#144]
https://github.com/OpenHFT/Chronicle-Wire/blob/19ad4bebf7143c4cbe0c04debf481fac0b3931bb/src/main/java/net/openhft/chronicle/wire/VanillaMethodWriterBuilder.java#L129

**Comment by JerryShea** [comment]
Leave this with me @AlexWibowoANZ

**Comment by RobAustin** [comment]
@AlexWibowoANZ yes I think so, I'll re-add it back in

**Comment by JerryShea** [comment]
@RobAustin as per our discussion :)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.45](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.45), [BOM-2.17.364](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.364)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
