### ISSUE TITLE
Added support for controlling the DocumentContext of a MethodWriter

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#145]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.45](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.45), [BOM-2.17.364](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.364)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
