### ISSUE TITLE
Improved error message when a class couldn't be found so a Tuple is used.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#147]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.51](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.51), [BOM-2.17.412](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.412)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
