### ISSUE TITLE
methodWriterInterceptor where not working because they where being overwritten with the methodWriterListener

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Wire#148]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.52](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.52), [BOM-2.17.423](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.423)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
