### ISSUE TITLE
make VanillaMethodReader easier to extend

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Wire#149]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.56](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.56), [BOM-2.17.449](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.449)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
