### ISSUE TITLE
Add support for generated code

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#150]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.60](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.60), [BOM-2.17.482](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.482)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.60](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.60), [BOM-2.17.496](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.496)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.60](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.60), [BOM-2.17.537](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.537)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.60](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.60), [BOM-2.17.541](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.541)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.60](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.60), [BOM-2.17.544](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.544)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.60](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.60), [BOM-2.17.546](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.546)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
