### ISSUE TITLE
JSON better handling or Double.Nan

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Wire#153]
JSON spec says that Double.NaN should be sent as 'null'

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.66](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.66), [BOM-2.17.522](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.522)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.66](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.66), [BOM-2.17.537](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.537)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.66](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.66), [BOM-2.17.541](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.541)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.66](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.66), [BOM-2.17.544](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.544)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.66](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.66), [BOM-2.17.546](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.546)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
