### ISSUE TITLE
Regression: MethodReader to handle all interfaces in class hierarchy

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Wire#154]

**Comment by JerryShea** [comment]
@peter-lawrey please review

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.69](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.69), [BOM-2.17.544](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.544)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.17.69](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.69), [BOM-2.17.546](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.546)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
