### ISSUE TITLE
BinaryWire.text(String s) creates unnecessary char arrays under newer Java versions

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Wire#155]
Under Java 8, Unsafe is invoked to obtain the underlying char[] in a String. However, if a newer Java version is used then `String::toCharArray` is invoked which will create a copy. 

It would be better to use some non-copying way of writing the chars.

**Comment by minborg** [comment]
Even though Java 14 is not supported, the following illustrates the problem:

![image](https://user-images.githubusercontent.com/7457876/74550358-8de8a200-4f51-11ea-9267-1716bf60d8cc.png)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.19.9](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.19.9), [BOM-2.19.111](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.111)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.19.9](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.19.9), [BOM-2.19.112](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.112)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.19.9](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.19.9), [BOM-2.19.116](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.116)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
