### ISSUE TITLE
Removed garbage from net.openhft.chronicle.wire.AbstractMethodWriterInvocationHandler

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Wire#158]
net.openhft.chronicle.wire.AbstractMethodWriterInvocationHandler create garbage:

The lambda called from net.openhft.chronicle.wire.AbstractMethodWriterInvocationHandler:53 is the culprit.

![image](https://user-images.githubusercontent.com/6506056/78123731-89dfe900-7406-11ea-803c-fa4d9c4405a6.png)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.19.2](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.19.2), [BOM-2.19.60](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.60)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.19.2](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.19.2), [BOM-2.19.62](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.62)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.19.2](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.19.2), [BOM-2.19.63](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.63)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.19.2](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.19.2), [BOM-2.19.64](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.64)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
