### ISSUE TITLE
clean up MethodWriter interceptors

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Wire#159]
Right now we have 

* MethodReaderInterceptor - deprecated
* MethodReaderInterceptorReturns - the latest version 

and for MethodWriter we have

* MethodWriterListener - deprecated as part of this issue
* MethodWriterInterceptor - deprecated
* MethodWriterInterceptorReturns - the latest version

**Comment by JerryShea** [comment]
See also #148 - IMHO we should *not* allow the user to specify a MethodWriterListener as well as a MethodWriterInterceptor/MethodWriterInterceptorReturns. We should only allow one and if they want to chain them then they can.

**Comment by JerryShea** [comment]
We now have UpdateInterceptor too which is currently only implemented for generated code (see MethodWriterProxyTest). Should we also implement default overloads for >1 arguments?

Also comment from @peter-lawrey in https://github.com/OpenHFT/Chronicle-Wire/issues/185

**Comment by JerryShea** [comment]
Have also committed some extra tests (with @Ignores) to show proxy generated MethodWriters vs generated code.

**Comment by RobAustin** [comment]
As discussed I will ensure that the UpdateInterceptor works with our use of the Java Proxies, and deprecate the MethodWriterInterceptor/MethodWriterInterceptorReturns and all code that uses MethodWriterInterceptor/MethodWriterInterceptorReturns should be changed to use the UpdateInterceptor.

**Comment by RobAustin** [comment]
So we will go from this:

* MethodWriterListener - deprecated as part of this issue
* MethodWriterInterceptor - deprecated
* MethodWriterInterceptorReturns - the latest version

to this:

* MethodWriterListener - deprecated as part of this issue
* MethodWriterInterceptor - deprecated
* MethodWriterInterceptorReturns - deprecated 
* UpdateInterceptor - the latest version

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.29](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.29), [BOM-2.20.56](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.56)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
