### ISSUE TITLE
Review and FIX outstanding issues with YamlWire.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#161]
The code needs a review to see if it can be improved structurally.

Some of the "improvements" break other types of wire esp delta wire

**Comment by jonatino** [comment]
Does this include removing the deviations from the YAML spec? Just curious as to why some features in  the YamlWire do not follow the standard YAML spec.

**Comment by peter-lawrey** [comment]
@Jonatino There should be a minimum of deviations and certainly they should be documented.

**Comment by alamar** [comment]
A lot of issues were fixed as a part of #402 but some features still remain unimplemented.

**Comment by alamar** [comment]
I will close this ticket since it lacks focus - our implementation should now be robust and we can file specific tickets for missing functionality or bugs.
