### ISSUE TITLE
VanillaMethodWriterBuilder generated proxies don't compile when running in maven tests

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Wire#162]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.14](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.14), [BOM-2.20.36](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.36)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
