### ISSUE TITLE
Improve consistency of TextWire. and writingDocument()

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#163]
writingDocument() doesn't do much when using pure text so was a bit hacky and inconsistent.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
