### ISSUE TITLE
MethodWriters:  removed the use of the Proxy

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Wire#164]
Removed the use of the Proxy.newProxyInstance and instead use code generation to create the method writers. The motivation for this is it gives us shorter call stacks.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.19.72](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.19.72), [BOM-2.19.351](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.351)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
