### ISSUE TITLE
MethodWriter byte argument fails to compile

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Wire#167]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.19.71](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.19.71), [BOM-2.19.347](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.347)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
