### ISSUE TITLE
MethodWriterBuilder: added updateInterceptor() to replace methodWriterInterceptorReturns()

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Wire#171]
The

```
MethodWriterBuilder<T> updateInterceptor(UpdateInterceptor updateInterceptor);
```

works better with the new code generator and hence replaces the methodWriterInterceptorReturns which relies on the code working with a Proxy.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
