### ISSUE TITLE
 JVM crashes in Wires class initializer

### ISSUE THREAD

**Issue by nrosl** [OpenHFT/Chronicle-Wire#175]
Was crashing inside jit compiler. Disabled JIT for dignostic purposes, got hs_err file with following stack trace:
Stack: [0x00007f28a03ff000,0x00007f28a0500000],  sp=0x00007f28a04fadb0,  free space=1007k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x564b8e]  Dictionary::find(int, unsigned int, Symbol*, ClassLoaderData*, Handle, Thread*)+0x8e
V  [libjvm.so+0xa43797]  SystemDictionary::resolve_instance_class_or_null(Symbol*, Handle, Handle, Thread*)+0x187
V  [libjvm.so+0xa45273]  SystemDictionary::resolve_or_fail(Symbol*, Handle, Handle, bool, Thread*)+0x33
V  [libjvm.so+0xaab2cf]  VerificationType::is_reference_assignable_from(VerificationType const&, ClassVerifier*, bool, Thread*) const+0xef
V  [libjvm.so+0xaae6ce]  ClassVerifier::verify_exception_handler_table(unsigned int, char*, int&, int&, Thread*)+0x35e
V  [libjvm.so+0xab89c5]  ClassVerifier::verify_method(methodHandle, Thread*)+0x4a5
V  [libjvm.so+0xabed6b]  ClassVerifier::verify_class(Thread*)+0xcb
V  [libjvm.so+0xabf4b5]  Verifier::verify(instanceKlassHandle, Verifier::Mode, bool, Thread*)+0x525
V  [libjvm.so+0x6495b7]  InstanceKlass::link_class_impl(instanceKlassHandle, bool, Thread*)+0x377
V  [libjvm.so+0x64c2bf]  InstanceKlass::initialize_impl(instanceKlassHandle, Thread*)+0x6f
V  [libjvm.so+0x64c7b1]  InstanceKlass::initialize(Thread*)+0x41
V  [libjvm.so+0x7fde0f]  LinkResolver::resolve_field(fieldDescriptor&, KlassHandle, Symbol*, Symbol*, KlassHandle, Bytecodes::Code, bool, bool, Thread*)+0x4df
V  [libjvm.so+0x7fe075]  LinkResolver::resolve_field_access(fieldDescriptor&, constantPoolHandle, int, Bytecodes::Code, Thread*)+0x245
V  [libjvm.so+0x68c4c5]  InterpreterRuntime::resolve_get_put(JavaThread*, Bytecodes::Code)+0x125
**j  net.openhft.chronicle.wire.Wires.<clinit>()V+112**
v  ~StubRoutines::call_stub
V  [libjvm.so+0x695ae6]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0x1056
V  [libjvm.so+0x649dca]  InstanceKlass::call_class_initializer_impl(instanceKlassHandle, Thread*)+0xda
V  [libjvm.so+0x64c591]  InstanceKlass::initialize_impl(instanceKlassHandle, Thread*)+0x341
V  [libjvm.so+0x64c7b1]  InstanceKlass::initialize(Thread*)+0x41
V  [libjvm.so+0x8010e6]  LinkResolver::resolve_static_call(CallInfo&, KlassHandle&, Symbol*, Symbol*, KlassHandle, bool, bool, Thread*)+0x246
V  [libjvm.so+0x80136f]  LinkResolver::resolve_invokestatic(CallInfo&, constantPoolHandle, int, Thread*)+0x23f
V  [libjvm.so+0x802431]  LinkResolver::resolve_invoke(CallInfo&, Handle, constantPoolHandle, int, Bytecodes::Code, Thread*)+0x501
V  [libjvm.so+0x68f159]  InterpreterRuntime::resolve_invoke(JavaThread*, Bytecodes::Code)+0x1b9
j  net.openhft.chronicle.wire.WireInternal.readData(Lnet/openhft/chronicle/wire/WireIn;Lnet/openhft/chronicle/wire/ReadMarshallable;Lnet/openhft/chronicle/wire/ReadMarshallable;)Z+65
j  net.openhft.chronicle.wire.WireIn.readDocument(Lnet/openhft/chronicle/wire/ReadMarshallable;Lnet/openhft/chronicle/wire/ReadMarshallable;)Z+3

java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

**Comment by dpisklov** [comment]
It seems you either have some dependencies missing or version mishmash. Are you using Maven? If so, are you using chronicle-bom or individual versions?

**Comment by nrosl** [comment]
Version mismatch of internal chronicle libraries? Yes using maven, picking individual versions.
Interestingly enough this crash doesn't happen consistently, but only when transferring certain data over the wire(to be isolated). 

			<dependency>
				<groupId>net.openhft</groupId>
				<artifactId>compiler</artifactId>
				<version>2.3.1</version>
			</dependency>

			<dependency>
				<groupId>net.openhft</groupId>
				<artifactId>chronicle-threads</artifactId>
				<version>1.16.4</version>
			</dependency>

			<dependency>
				<groupId>net.openhft</groupId>
				<artifactId>chronicle-bytes</artifactId>
				<version>1.16.26</version>
			</dependency>



			<dependency>
				<groupId>net.openhft</groupId>
				<artifactId>chronicle-core</artifactId>
				<version>1.16.26</version>
			</dependency>

			<dependency>
				<groupId>net.openhft</groupId>
				<artifactId>chronicle-wire</artifactId>
				<version>1.16.18</version>
			</dependency>

**Comment by RobAustin** [comment]
Please use the versions grouped in the chronicle-Bom and retest. ( please let us know if you still see it when using the BOM )

**Comment by nrosl** [comment]
The problem was an undersized buffer. Not exactly sure how it corrupted the symbol table, but increasing the buffer space fixed the issue.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
