### ISSUE TITLE
Sequences don't require comma-space just comma as seperator

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#181]
Even though all examples in https://yaml.org/spec/1.2/spec.html have a white space after a comma, and a colon needs a whitespace, a comma doesn't.

**Comment by RobAustin** [comment]
thanks

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
