### ISSUE TITLE
Add MilliTimestampLongConverter and change autoconvert to a warning

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#183]
Add `MilliTimestampLongConverter` to ease the migration and make longs read as dates to be a warning, not replaced implicitly.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.3](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.3), [BOM-2.20.7](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.7)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.3](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.3), [BOM-2.20.12](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.12)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.3](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.3), [BOM-2.20.17](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.17)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
