### ISSUE TITLE
Use correct start and end of document separators as per YAML v1.2

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#186]
In x.19, the TextWire used `---` between documents, however it used them at the end of each document.

In x.20, TextWire will use `---` for the start of document and `...` for the end of document as per the YAML v1.2 standard.

**Comment by peter-lawrey** [comment]
For test outputs which need to rebuilt, the `-Dregress.tests` option will be used.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.6](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.6), [BOM-2.20.22](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.22)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
