### ISSUE TITLE
Added support for generating a JSON schema for a Methodreader/Writer

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#187]

**Comment by RobAustin** [comment]
@peter-lawrey Im going to close this, as it looks done, please reopen if you disagree

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
