### ISSUE TITLE
UpdateInterceptor to support primitive arguments

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Wire#190]
Logs a warning to tell user there will be boxing

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.13](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.13), [BOM-2.20.35](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.35)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
