### ISSUE TITLE
Default methods should be given an implementation for MethodWriters by default.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#192]
The handling of the call to a `default` method can be handled by the MethodReader side.

**Comment by RobAustin** [comment]
The problem is that the Method Writers are not writing the default methods to the chronicle queue

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
