### ISSUE TITLE
Make top level configuration DTO also Events so they can be passed to services and changed on the fly.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#194]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
