### ISSUE TITLE
MethodReader throws when same interface in class hierarchy more than once

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Wire#195]
e.g.
```
interface Interface {...
class Parent implements Interface {...
class Child extends Parent implements Interface {...
```
generating an MR for Child blows up

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
