### ISSUE TITLE
Improved support for dynamic enums

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#196]
Reference data can be stored in `enum` however this can make them too static.

As an extension, support for adding or changing the data associated with an enum on the fly broadens the use case for enums.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
