### ISSUE TITLE
ChronicleReader fails to read BytesInBinaryMashallable object

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#198]
The `BinaryWire.copyTo()` has been altered to read DTOs which are not SelfDescribingMarshallable by deserializing them and writing them.

NOTE: This requires that non-self-describing DTOs be on the classpath to be decoded correctly.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
