### ISSUE TITLE
Added support for mapping interfaces to a default implementation

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#200]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.28](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.28), [BOM-2.20.51](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.51)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
