### ISSUE TITLE
Simplified the chained vs nested WriteDocumentContext by adding chainedElement() flag

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#211]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.64](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.64), [BOM-2.20.84](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.84)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
