### ISSUE TITLE
Generated method reader fails to compile in case lambda instance is passed

### ISSUE THREAD

**Issue by glukos** [OpenHFT/Chronicle-Wire#216]

**Comment by glukos** [comment]
Covered by MethodReaderNonStandardInstancesTest

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.67](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.67), [BOM-2.20.87](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.87)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
