### ISSUE TITLE
Generated method writer fails to compile if interface chaining return type is a nested class

### ISSUE THREAD

**Issue by glukos** [OpenHFT/Chronicle-Wire#219]
Please see MethodWriterNestedReturnTypeTest

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.84](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.84), [BOM-2.20.123](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.123)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
