### ISSUE TITLE
Method reader with an interceptor may be not initialized properly in case it's created concurrently from several threads

### ISSUE THREAD

**Issue by glukos** [OpenHFT/Chronicle-Wire#223]
Covered by MethodReaderInterceptorReturnsTest#testInterceptingReaderConcurrentCreation

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
