### ISSUE TITLE
Marshallable#reset behaviour change while trying change version to 2.20.63

### ISSUE THREAD

**Issue by EdShangGG** [OpenHFT/Chronicle-Wire#225]
https://github.com/EdShangGG/Chronicle-Wire/commit/c2f8ac6cafb344d7954f9be917b3bad39a71340d - reproducer.

On previous versions reset sets boolean fields to default value in all cases.
On 2.20.63 if boolean involved in close logic it would be set to value from close method not default one.

**Comment by RobAustin** [comment]
thanks,

**Comment by RobAustin** [comment]
Ive added the following test to chronicle wire - net.openhft.chronicle.wire.WireResetTest

**Comment by RobAustin** [comment]
this issue is likely to be related to - https://github.com/OpenHFT/Chronicle-Wire/commit/4538e23736c5d44ea79ab1460cd6b92d6f11e9dc

**Comment by RobAustin** [comment]
we have to close the default objects, otherwise, the resource monitoring complains that they have not been closed. This is, unfortunately, changing the state of isClosed() back to true. The solution is not to monitor these default objects in the first place so that we don't have to close them.

**Comment by RobAustin** [comment]
@EdShangGG thanks for the test is was very helpful.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.84](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.84), [BOM-2.20.123](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.123)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
