### ISSUE TITLE
Delegation to vanilla method reader implementation doesn't work in case text wire is used

### ISSUE THREAD

**Issue by glukos** [OpenHFT/Chronicle-Wire#229]
In case TEXT or YAML wire is used and generated method reader fails to read a message, parsing should be delegated to a vanilla instance. However, erroneous message is not present in wire anymore: vanilla implementation just reads the next message.
The root cause is a not implemented `documentContext.rollbackOnClose();`.

How to reproduce: replace `BinaryWire` by `TextWire` in `MethodReaderDelegationTest`.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.102](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.102), [BOM-2.20.141](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.141)
