### ISSUE TITLE
Migrate GeneratingMethodWriter to use the form which supports debugging.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#231]
This is only enabled with the `wire.generate.v2` system property

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.102](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.102), [BOM-2.20.141](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.141)
