### ISSUE TITLE
Added support for generating a method delegate

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#232]
This is needed to support testing of services with a circular dependency between them

**Comment by peter-lawrey** [comment]
FYI @JerryShea

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.103](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.103), [BOM-2.20.142](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.142)
