### ISSUE TITLE
Inconsistent EnumSet marshalling order

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Wire#238]
When enums were added, sometimes ordering of elements changed

**Comment by JerryShea** [comment]
From https://docs.oracle.com/javase/8/docs/api/java/util/EnumSet.html "The iterator returned by the iterator method traverses the elements in their natural order (the order in which the enum constants are declared).". EnumSet.toString also respects this natural order.

We should write out elements in this natural order - currently we write themin reverse order for some reason.

This could impact customer yaml tests.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.108](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.108), [BOM-2.20.161](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.161)
