### ISSUE TITLE
TextMethodTester execute multiple setups

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Wire#239]
Customer requirement

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.108](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.108), [BOM-2.20.161](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.161)
