### ISSUE TITLE
Ensure we call Wires static block before generating any code, so as to ensure classpath set up

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Wire#241]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.109](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.109), [BOM-2.20.178](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.178)
