### ISSUE TITLE
Document MethodIds

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Wire#244]
Wire doco needs a review and revamp

**Comment by foroughgoudarzi** [comment]
@JerryShea, @RobAustin, @minborg The documentation was improved.

**Comment by minborg** [comment]
Please review the changes made by @foroughgoudarzi and the `demo` module where users can actually run the examples shown in the docs.

**Comment by JerryShea** [comment]
Documentation looks good but still no mention of MethodIds

**Comment by foroughgoudarzi** [comment]
The MethodId was added.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.21ea41](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.21ea41), [BOM-2.21ea113](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea113)
