### ISSUE TITLE
TextMethodTester pluggable handling for RuntimeInvocationTargetException

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Wire#245]
Follow on from #243

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.112](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.112), [BOM-2.20.201](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.201)
