### ISSUE TITLE
Maps with key objects not serialized as expected for YAML and JSON

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#246]
In particular, for JSON this is invalid.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.112](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.112), [BOM-2.20.201](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.201)
