### ISSUE TITLE
One question about serilizing JSON with comlicated key-value

### ISSUE THREAD

**Issue by SouthernYard** [OpenHFT/Chronicle-Wire#251]
Hi team,

Recently, I was tried to parse a complicated JSON string to a Wire object. But if the key-value is complicated like the following sample('tick' or 'asks'),  I must convert the key-value to an object. 
```JSON
{
    "ch":"topic",
    "ts":1608944404989,
    "tick":{
        "asks":[
            [
                24599.19,
                0
            ]
        ]
    }
}
```
```Java
// the JSON has been converted to a Wire object.
wire.read(() -> "tick").object();
// or
wire.read(() -> "tick").object(Tick.class);
```
So my question is: is there any possible approach to access the 'tick' or 'asks' to avoid creating new objects? 
Look forward to your reply.

Thanks,
Shawn

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.21ea6](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.21ea6), [BOM-2.21ea36](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea36)
