### ISSUE TITLE
TextWire use ObjectUtils.implementationToUse in preference to Wires.tupleFor

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Wire#255]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.21ea3](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.21ea3), [BOM-2.21ea21](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea21)
