### ISSUE TITLE
Remove object creation when using @LongConverters calling asText()

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Wire#256]
Many of the converts are relying on the base default method for asText() these create a StringBuilder each time.

![image](https://user-images.githubusercontent.com/6506056/105735119-3f969e00-5f2b-11eb-9ede-64cda5727b85.png)
0

The converters are stateless, however, using a thread-local may be a better choice than creating an object. 
consider using: 

```
Wires.acquireStringBuilder()
```

**Comment by JerryShea** [comment]
@RobAustin I believe this is done so closing

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.21ea41](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.21ea41), [BOM-2.21ea113](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea113)
