### ISSUE TITLE
Low garbage de/serialisation of LocalDate

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Wire#259]

**Comment by JerryShea** [comment]
@peter-lawrey is this complete?

**Comment by peter-lawrey** [comment]
Yes.

**Comment by peter-lawrey** [comment]
I thought it was closed for some reason.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.21ea8](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.21ea8), [BOM-2.21ea47](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea47)
