### ISSUE TITLE
Wires.copyTo now works for mismatched BytesInBinaryMarshallable objects

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#260]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.21ea8](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.21ea8), [BOM-2.21ea47](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea47)
