### ISSUE TITLE
PerfRegressionTest fails to run stably within expected performance bounds

### ISSUE THREAD

**Issue by glukos** [OpenHFT/Chronicle-Wire#267]
https://teamcity.chronicle.software/viewLog.html?buildId=557482&tab=buildResultsDiv&buildTypeId=OpenHFT_ChronicleWire_Snapshot
https://teamcity.chronicle.software/viewLog.html?buildId=557494&tab=buildResultsDiv&buildTypeId=OpenHFT_BuildAll_Build

**Comment by JerryShea** [comment]
Do we need a TeamCity performance agent? Or do we run a performance verification job at the weekend only when things are quieter?

**Comment by minborg** [comment]
Got closed by accident

**Comment by glukos** [comment]
Closing as not actual anymore.
