### ISSUE TITLE
TextWire fails to consume token after null

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Wire#269]
In TextWire, the `isNull()` check seems to leave the input buffer in a position where the next field key cannot be read:

 ```
@Override

public boolean isNull() {

    consumePadding();
 

    if (peekStringIgnoreCase("!!null \"\"")) {

        bytes.readSkip("!!null \"\"".length());

        // discard the text after it.

        //  text(acquireStringBuilder());

        return true;

    }

    return false;

}
```
 
In our example we have the following fields:

```
private byte[] allowedPools;

private OrderLevel orderLevel = PARENT;
```
 

Which look like this on the wire:

`\n allowedPools: !!null””,\n orderLevel: PARENT`

After reading the allowedPools key / value, the buffer looks like this:

 
`,\n orderLevel: PARENT`

 
The next read consumes the leading ‘,’ character as the key, instead of ‘orderLevel’, leaving:
 
`\n orderLevel: PARENT`
 

The value read fails at this point because the value read, `orderLevel`, is not a valid enum type.

 
We’re using BOM 2.20.210

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.21ea41](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.21ea41), [BOM-2.21ea113](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea113)
