### ISSUE TITLE
Read array of unknown length?

### ISSUE THREAD

**Issue by jonatino** [OpenHFT/Chronicle-Wire#270]
Trying to implement Chronicle Wire as the backend for a yaml based saving system for players. The problem I've ran into there doesn't seem to be a way to read the saved array without knowing its length. This is not possible as the arrays saved are not always a constant size, and can vary player to player.

```kotlin
class BooleanArrayType(key: String) : SaveType<BooleanArray>(key) {
	override fun load(wire: Wire, defaultValue: () -> BooleanArray) = wire.read(key).array()// The size of the array is unknown at load time
	override fun save(wire: Wire, value: BooleanArray) = wire.write(key).array(value, value.size)
}
```

I've checked the wire API's and did not find any method for getting the length of an array needed for the current wirevalue.

Is this possible? What's the most efficient way about doing this.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.21ea41](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.21ea41), [BOM-2.21ea113](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea113)
