### ISSUE TITLE
Force unique keys for YamlWire

### ISSUE THREAD

**Issue by jonatino** [OpenHFT/Chronicle-Wire#271]
Currently if you write two of the same keys back to back, it will result in duplicate entries with the same keys in the output.

Eg.
```kotlin
fun testMultipleSaves() {
    val buffer: Bytes<ByteBuffer> = Bytes.elasticByteBuffer(2000)
    val outWire: Wire = YamlWire(buffer)
    outWire.write("test").text("this is the first test")
    outWire.write("test").text("this is my updated test")
    println(outWire)
}
```

Output: 
```yaml
test: this is the first test
test: this is my updated test
```

Is there anyway to configure the wire to update the previous entry if a duplicate key is detected? Which would result in the following output:
```yaml
test: this is my updated test
```

Note the first entry was removed as the key was duplicated and instead replaced with the updated value

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.21ea41](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.21ea41), [BOM-2.21ea113](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea113)
