### ISSUE TITLE
Created a net.openhft.chronicle.wire.DoubleConversion that can be used to round the text yaml representation on doubles

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Wire#283]
"when writing the integration test for the neural network demo, I’ve come to request that the YAML tester can tolerate certain deviations (epsilon) for float fields. Even though the neural network is deterministic once trained, it is more practical to stipulate that an output lies within some threshold, rather than providing the exact float with 20 decimals in the out.yaml. I know the current YAMLtester performs String comparison, hence this would complicate the implementation quite a bit, but it would certainly be very useful. Just a thought."  - Julia

**Comment by peter-lawrey** [comment]
The simplest solution is to add an `afterRun` function to the `TextMethodTester` which can parse or use a `s.replaceAll()` to manipulate the actual result.
