### ISSUE TITLE
WireResourcesTest failures

### ISSUE THREAD

**Issue by scottkidder** [OpenHFT/Chronicle-Wire#29]
testMappedBytesClose and testMappedBytesWireRelease2 now fail with latest Bytes.

**Comment by RobAustin** [comment]
which version is failing for you, can you retest with the latest snapshot, as its not failing for me.

**Comment by peter-lawrey** [comment]
These tests have been passing for a while, closing for now.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
