### ISSUE TITLE
Is there a way to throw exception on unexpected field?

### ISSUE THREAD

**Issue by apoorva-sriv** [OpenHFT/Chronicle-Wire#290]
Instead of logging a warning [here](https://github.com/OpenHFT/Chronicle-Wire/blob/ae96b8582feb245a2392566fa8156a22bb24801e/src/main/java/net/openhft/chronicle/wire/AbstractMarshallableCfg.java#L38), is there a way to throw an exception or detect the warning? I'm using `Marshallable.fromFile()` to check that `yaml` files parse correctly and want to fail the test if there is an unexpected field warning.

**Comment by RobAustin** [comment]
take a look at net.openhft.chronicle.core.Jvm.setExceptionHandlers(..,..,..)
