### ISSUE TITLE
JSON wire fails to parse comma-separated array in complex cases

### ISSUE THREAD

**Issue by glukos** [OpenHFT/Chronicle-Wire#292]
```
    @Test
    @Ignore
    public void testArrayInDictionary() {
        String text = "[1,{\"a\":[2,3]}]";

        final JSONWire jsonWire = new JSONWire(Marshallable.<Bytes<ByteBuffer>>fromString(text));

        final List<Object> list = jsonWire.getValueIn().list(Object.class);

        assertNotNull(list);
    }
```

**Comment by glukos** [comment]
The issue in this particular test is extra closing brace ']'
I'll update the test if I get to the real issue.

**Comment by glukos** [comment]
@peter-lawrey The issue is actually with array elements that are split by comma "," without a space. Adding space to the delimeter fixes the issue.
For some reason it works for simple arrays (like [1,2,3]).

**Comment by peter-lawrey** [comment]
In YAML, a comma must be followed by a whitespace or special character, however in JSON, a simple comma is always a seperator. e.g.

Has one element in YAML, three elements in JSON.
```yaml
[1,2,3]
```

**Comment by peter-lawrey** [comment]
Note: In YAML, this list has two strings `1,2,3` and `c`

```
[1,2,3, c]
```
