### ISSUE TITLE
Fix some tests which were producing warnings

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#295]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.21ea84](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.21ea84), [BOM-2.21ea207](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea207)
