### ISSUE TITLE
HashWire is non-binary (text) wire which leads to object allocation, CPU usage

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Wire#307]
We have `HashWire` used to calculate hash codes of `SelfDescribingMarshallable`, which is a text wire (it does not override `isBinary()` to return true). Which leads to easy 6-7x CPU usage as well as object allocations. 

I guess we can't change it since it will affect existing objects' hash codes, which could be stored by our users. Maybe we can introduce a system property to make it use the binary form, which we will then make the default (in 2.23 or 3.X?)

**Comment by JerryShea** [comment]
I personally think it is OK to change the hash value now, in x.22

**Comment by alamar** [comment]
I suggest doing that by default in 2.24
@minborg Should I reassign it to myself?

**Comment by minborg** [comment]
Please do @alamar
