### ISSUE TITLE
Unexpected fields encountered reading a document context are visible in subsequent document contexts

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Wire#311]
This is the cause of https://github.com/ChronicleEnterprise/Chronicle-Queue-Enterprise/issues/258

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.22ea2](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.22ea2), [BOM-2.22ea29](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea29)
