### ISSUE TITLE
JavaDocs are missing

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Wire#316]
Many classes are not documented properly or even at all. These classes should either be documented or internalized (and still documented but perhaps less stringent).

- [ ] AbstractAnyWire.java
- [ ] AbstractClassGenerator.java
- [ ] AbstractCommonMarshallable.java
- [ ] AbstractEventCfg.java
- [ ] AbstractFieldInfo.java
- [ ] AbstractGeneratedMethodReader.java
- [ ] AbstractMarshallableCfg.java
- [ ] AbstractMethodWriterInvocationHandler.java
- [ ] AbstractTimestampLongConverter.java
- [ ] AbstractWire.java
- [ ] AsMarshallable.java
- [ ] Base128LongConverter.java
- [ ] Base256IntConverter.java
- [ ] Base32IntConverter.java
- [ ] Base32LongConverter.java
- [ ] Base40IntConverter.java
- [ ] Base40LongConverter.java
- [ ] Base64LongConverter.java
- [ ] Base85IntConverter.java
- [ ] Base85LongConverter.java
- [ ] Base95LongConverter.java
- [ ] BinaryMethodWriterInvocationHandler.java
- [ ] BinaryReadDocumentContext.java
- [ ] BinaryWire.java
- [ ] BinaryWireCode.java
- [ ] BinaryWireHighCode.java
- [ ] BinaryWriteDocumentContext.java
- [ ] BitSetUtil.java
- [ ] BracketType.java
- [ ] BytesInBinaryMarshallable.java
- [ ] CSVWire.java
- [ ] CharConversion.java
- [ ] CharConverter.java
- [ ] CharSequenceObjectMap.java
- [ ] ChronicleBitSet.java
- [ ] Comment.java
- [ ] CommentAnnotationNotifier.java
- [ ] DefaultValueIn.java
- [ ] Demarshallable.java
- [ ] DocumentContext.java
- [ ] DocumentContextHolder.java
- [ ] DocumentWritten.java
- [ ] DynamicEnum.java
- [ ] Event.java
- [ ] FieldInfo.java
- [ ] FieldNumberParselet.java
- [ ] GenerateJsonSchemaMain.java
- [ ] GenerateMethodBridge.java
- [ ] GenerateMethodDelegate.java
- [ ] GenerateMethodReader.java
- [ ] GenerateMethodWriter.java
- [ ] GenerateMethodWriter2.java
- [ ] GeneratedProxyClass.java
- [ ] GeneratingMethodReaderInterceptorReturns.java
- [ ] HashWire.java
- [ ] HeadNumberChecker.java
- [ ] HexadecimalIntConverter.java
- [ ] HexadecimalLongConverter.java
- [ ] InputStreamToWire.java
- [ ] IntConversion.java
- [ ] IntConverter.java
- [ ] JSONWire.java
- [ ] KeyedMarshallable.java
- [ ] LongArrayValueBitSet.java
- [ ] LongConversion.java
- [ ] LongConverter.java
- [ ] LongValueBitSet.java
- [ ] Marshallable.java
- [ ] MarshallableIn.java
- [ ] MarshallableOut.java
- [ ] MarshallableParser.java
- [ ] MessageHistory.java
- [ ] MessagePathClassifier.java
- [ ] MethodDelegate.java
- [ ] MethodFilter.java
- [ ] MethodFilterOnFirstArg.java
- [ ] MethodWireKey.java
- [ ] MethodWriter.java
- [ ] MethodWriterInvocationHandlerSupplier.java
- [ ] MethodWriterValidationException.java
- [ ] MethodWriterWithContext.java
- [ ] MicroDurationLongConverter.java
- [ ] MicroTimestampLongConverter.java
- [ ] MilliTimestampLongConverter.java
- [ ] NanoDurationLongConverter.java
- [ ] NanoTimestampLongConverter.java
- [ ] NoDocumentContext.java
- [ ] ObjectIntObjectConsumer.java
- [ ] OxHexadecimalLongConverter.java
- [ ] ParameterHolderSequenceWriter.java
- [ ] ParameterizeWireKey.java
- [ ] QueryWire.java
- [ ] Quotes.java
- [ ] RawText.java
- [ ] RawWire.java
- [ ] ReadAnyWire.java
- [ ] ReadDocumentContext.java
- [ ] ReadMarshallable.java
- [ ] ReadingMarshaller.java
- [ ] ReflectionUtil.java
- [ ] ScalarStrategy.java
- [ ] SelfDescribingMarshallable.java
- [ ] SelfDescribingTriviallyCopyable.java
- [ ] Sequence.java
- [ ] SerializationStrategies.java
- [ ] SerializationStrategy.java
- [ ] ServicesTimestampLongConverter.java
- [ ] SourceContext.java
- [ ] TextMethodTester.java
- [ ] TextMethodWriterInvocationHandler.java
- [ ] TextReadDocumentContext.java
- [ ] TextStopCharTesters.java
- [ ] TextStopCharsTesters.java
- [ ] TextWire.java
- [ ] TextWriteDocumentContext.java
- [ ] TriConsumer.java
- [ ] UnexpectedFieldHandlingException.java
- [ ] UnrecoverableTimeoutException.java
- [ ] UnsignedIntConverter.java
- [ ] UnsignedLongConverter.java
- [ ] ValueIn.java
- [ ] ValueInStack.java
- [ ] ValueInState.java
- [ ] ValueOut.java
- [ ] ValueWriter.java
- [ ] VanillaFieldInfo.java
- [ ] VanillaMessageHistory.java
- [ ] VanillaMethodReader.java
- [ ] VanillaMethodReaderBuilder.java
- [ ] VanillaMethodWriterBuilder.java
- [ ] VanillaWireParser.java
- [ ] WatermarkedMicroTimestampLongConverter.java
- [ ] Wire.java
- [ ] WireCommon.java
- [ ] WireDumper.java
- [ ] WireIn.java
- [ ] WireInternal.java
- [ ] WireKey.java
- [ ] WireMarshaller.java
- [ ] WireMarshallerForUnexpectedFields.java
- [ ] WireObjectInput.java
- [ ] WireObjectOutput.java
- [ ] WireOut.java
- [ ] WireParselet.java
- [ ] WireParser.java
- [ ] WireSerializedLambda.java
- [ ] WireToOutputStream.java
- [ ] WireType.java
- [ ] Wires.java
- [ ] WordsIntConverter.java
- [ ] WordsLongConverter.java
- [ ] WrappedDocumentContext.java
- [ ] WriteDocumentContext.java
- [ ] WriteMarshallable.java
- [ ] WriteValue.java
- [ ] WritingMarshaller.java
- [ ] YamlKeys.java
- [ ] YamlLogging.java
- [ ] YamlMethodTester.java
- [ ] YamlToken.java
- [ ] YamlTokeniser.java
- [ ] YamlWire.java

**Comment by RobAustin** [comment]
@minborg how did you run this report, maybe it's a stat that we can periodical refer to,

**Comment by minborg** [comment]
Don't remember I am afraid. Maybe there is a plugin for SQ that could keep track of this?

<img width="684" alt="image" src="https://user-images.githubusercontent.com/7457876/167150854-3bf0ec02-df01-4893-b200-1ffa65e10df5.png">

**Comment by RobAustin** [comment]
I'm going to close this as we should break it down into many separate tasks
