### ISSUE TITLE
Add an example of a map-like usage of reusable Lists

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Wire#317]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.22ea3](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.22ea3), [BOM-2.22ea29](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea29)
