### ISSUE TITLE
Added a ChronicleBitSet with a packed array of 64-bit words to be more efficient

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#321]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.22ea5](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.22ea5), [BOM-2.22ea33](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea33)
