### ISSUE TITLE
The typed JSON generator creates unbalanced output wrt brackets

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Wire#325]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.22ea7](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.22ea7), [BOM-2.22ea40](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea40)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.22ea8](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.22ea8), [BOM-2.22ea48](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea48)
