### ISSUE TITLE
De-serialization fails to populate the array fields.

### ISSUE THREAD

**Issue by chauhraj** [OpenHFT/Chronicle-Wire#33]
I am using Chronicle-Queue(CQ) and Chronicle Map(CM) which pulls in the Chronicle Wire v1.7.6 . I am able to the write the object into CQ without any issue. This object model has fields which are of array type. So, when CQ tries to reading off the object, it fails to populate the array field and throws exception `IlegalArgumentException: Argument is not an array`. 

I tried debugging through the code and control goes through [BinaryWire.java](https://github.com/OpenHFT/Chronicle-Wire/blob/c0d77d4c6af852b0718a13e84bfc7d8d56763a6c/src/main/java/net/openhft/chronicle/wire/BinaryWire.java#L2527) where it is attempting to populate the object with the values. In this method, in the accept invocation of the passed lambda, the object itself is passed. I feel that the actual array instance should have been created and stored in the passed object and this array instance should have been passed. What happens in [WireMarshaller.java](https://github.com/OpenHFT/Chronicle-Wire/blob/c0d77d4c6af852b0718a13e84bfc7d8d56763a6c/src/main/java/net/openhft/chronicle/wire/WireMarshaller.java#L373), when it checks Array.getLength(array), it results in IllegalArgumentException.

LMK, if you need any further details. Just for the sake of completeness, it is a scala application and the Arrays component type are Java enums with their name as the values in the array.

**Comment by peter-lawrey** [comment]
What would be helpful is some unit tests. We would be happy to take a PR
and use this to fix the code.

Regards,
Peter.

**Comment by chauhraj** [comment]
I would love to contribute a fix. But, I appreciate some hand holding here as I am not intimately aware of the code base. For instance, where to put the Junit testcase and any guidelines that I need to follow.

**Comment by peter-lawrey** [comment]
First you fork the repo and work off your fork.

I suggest you put them under

src/test/java

where the other classes called *Test are. Have a look at one o f the tests
you think is simple. Copy it and modify it.

**Comment by peter-lawrey** [comment]
I have added some tests and fixed two bugs in this area. Could you re-test or add your own?

**Comment by chauhraj** [comment]
Added the testcase. With this testcase, I was able to reproduce the error. I saw your fix and initially, I thought of the same approach but I didnt go ahead with this because this is going to create garbage though short lived one. Maybe, it is Ok. However, I tried to look into using int64array method and realized that it is getting two complicated. Mainly, I was struggling with how to get the size of the array without using Collection. To do that, it would have required to know the size of the array which means there would be a change in write method.

Anyways, it doesn't matter any more. However, I added the testcase and was able to reproduce the issue. Here is the PR corresponding to this fix.

https://github.com/OpenHFT/Chronicle-Wire/pull/34

**Comment by peter-lawrey** [comment]
The most important thing is correctness first. Later we can worry about
performance and garbage creation.

**Comment by peter-lawrey** [comment]
Thank you for the fix merged, tests all pass.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
