### ISSUE TITLE
Unreadable messages when marshalling object or generic fields containing BytesMarshallable

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Wire#334]
The following test case: https://gist.github.com/alamar/4c78d0b9bd9a2d41402662fbd6dccffa

When we have an Object/<T> field in a class, and the value of that field is BytesMarshallable but not SelfDescribingMarshallable, the type information is lost which will lead to undefined behavior upon deserialization. At least a warning should be printed in such cases.

Discovered together with @glukos

**Comment by alamar** [comment]
Incidentally it was working in chronicle-wire 2.20.24

**Comment by alamar** [comment]
cd3feddac04a1427eb501cb123aa049bcd9f8664 is the first bad commit

**Comment by alamar** [comment]
The commit seems to have a misplaced message, looks like it introduces marshalling of BytesMarshalalble objects into BinaryWire. It has likely caused the issue since the type information was lost.

**Comment by alamar** [comment]
I have discovered a legitimate case of writing, and reading object of unspecified type: `BinaryIntArrayReference` is used in place of `IntArrayValues` in `TwoArraysTest` by unmarshalling into an existing object. So it should probably be just a warning.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.22ea12](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.22ea12), [BOM-2.22ea79](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea79)
