### ISSUE TITLE
Character '\0xFFFF' turned to zero after unmarshalling

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Wire#344]
If a `char` field contains `0xFFFF`, after marshalling and unmarshalling it would contain `0`.

Wire seems to treat `0xFFFF` as an unset char value, but it will overwrite the unset char field with 0 instead.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.22ea11](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.22ea11), [BOM-2.22ea69](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea69)
