### ISSUE TITLE
Fixed JSON Wire with ZoneID

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Wire#347]
see failing test - net.openhft.chronicle.wire.TestMarshallableZoneId

**Comment by minborg** [comment]
ZoneID is `abstract` to it is only to be expected that the test fails. Previously it was assumed abstract classes should be set to `null` when no `using` is provided. I think it is better if an exception is thrown.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.22ea11](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.22ea11), [BOM-2.22ea69](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea69)
