### ISSUE TITLE
Text formatting of multiple objects within a sequence omits element separator

### ISSUE THREAD

**Issue by ryanlea** [OpenHFT/Chronicle-Wire#35]
Perhaps I'm misusing marshallable within sequence?  However, it doesn't print out the element separators for multiple objects within a sequence.  The result is invalid yaml.

The output can, however, be read back in by Chronicle-wire.  Interesting to note that the JsonWire extension overrides pushState() to set leaf() in this case as well - unsure if that would resolve.

gist of the test case attached below.

Cheers

Ryan

Gist:  https://gist.github.com/ryanlea/5547d80f04f65b2d506528effc0f4330

**Comment by peter-lawrey** [comment]
Thank you for the test case. I will look into it tomorrow.

**Comment by peter-lawrey** [comment]
I suspect this was fixed a couple of weeks ago. Can you check this test? It loads with snakeYaml.

**Comment by peter-lawrey** [comment]
Closing for now as test passes. Can reopen if this isn't fixed.

**Comment by ryanlea** [comment]
Apologies for tardy response.  Yes, this appears fixed - tested with 1.7.18.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.22ea11](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.22ea11), [BOM-2.22ea69](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea69)
