### ISSUE TITLE
Optimize SerializeJavaLang::parseDate

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Wire#353]
The said method could be optimized in terms of performance.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.22ea11](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.22ea11), [BOM-2.22ea69](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea69)
