### ISSUE TITLE
Remove support for parsing non-marshallable object properties from TEXT wire root

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Wire#357]
The last changes disallow having a non-Marshallable object whose properties are taken from root wire context, in properties-file style (see test). We need to check this case explicitly and capture the current behavior.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.22ea11](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.22ea11), [BOM-2.22ea69](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea69)
