### ISSUE TITLE
Allow non serializable field types if they have been set to null

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#365]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.22ea11](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.22ea11), [BOM-2.22ea69](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea69)
