### ISSUE TITLE
chronicle-queue 5.21.91 does not properly work with java.util.Date

### ISSUE THREAD

**Issue by olegs1993** [OpenHFT/Chronicle-Wire#367]
Hi, when I am trying to write the java.util.Date object looks like it is cutting off milliseconds:
![image](https://user-images.githubusercontent.com/23138783/145840139-a59e352d-15a2-48fb-ba04-9d80c8d52c72.png)

After small the small investigation I have found the code change in the ValueOut interface:
![image](https://user-images.githubusercontent.com/23138783/145839752-7783746a-b801-428c-ac7c-6ab1821a22b9.png)

So, it's using the toString method now, that's why the logic is broken.
Could someone take a look at this, please? is it a bug?

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea9](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea9), [BOM-2.23ea44](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea44)
