### ISSUE TITLE
NPE when using @LongConversion(Base40LongConverter.class) 

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Wire#370]
See unit test

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.22ea12](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.22ea12), [BOM-2.22ea79](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea79)
