### ISSUE TITLE
There's no way to tell if a value was present

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Wire#378]
Currently when reading from a `WireIn`, if you call
```
ValueIn valueIn = wireIn.read("fieldName");
```

the only way to determine if the field was present is
```
boolean wasPresent = valueIn instanceof DefaultValueIn;
```

It feels like there should be a way to do this via the `ValueIn` interface, rather than reaching under the hood in this way and relying on implementation details.

### Proposed solution
My proposed solution is to add a method `boolean isPresent()` to the `ValueIn` interface. `DefaultValueIn` could return `false` for this and every `ValueIn` that represented a present value could return `true`.

**Comment by minborg** [comment]
Sounds good to me. I think the increased API surface would be justified as it would reduce access to internal structures and would improve user code. Maybe there are other things from the Optional/Stream class that can be incorporated in a future rewrite of Wire?

**Comment by rogersimmons** [comment]
+1

**Comment by nicktindall** [comment]
> Sounds good to me. I think the increased API surface would be justified as it would reduce access to internal structures and would improve user code. Maybe there are other things from the Optional/Stream class that can be incorporated in a future rewrite of Wire?

Ooh yes, orElse or orElseThrow would be really useful... they don't really fit the API currently
