### ISSUE TITLE
Wire to use the ClassLookup it holds if set, instead of the global ClassAliasPool

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#380]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.22ea15](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.22ea15), [BOM-2.22ea121](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea121)
