### ISSUE TITLE
Added a test with different number types as keys

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#383]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.21.94](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.21.94), [BOM-2.21.256](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21.256)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.22ea15](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.22ea15), [BOM-2.22ea121](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea121)
