### ISSUE TITLE
Added support for pass through of flow wires

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#387]
This is needed to support and test routers so they can treat portions of messages generically without any specific knowledge of the contents of the meassage

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.22ea15](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.22ea15), [BOM-2.22ea121](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea121)
