### ISSUE TITLE
Error reading an object containing a Map.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#40]
Based on [OpenHFT/Chronicle-Queue] TreeMap encoding Issue (#321)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
