### ISSUE TITLE
Improve efficiency of (de)marshalling byte[]

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#405]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea1](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea1), [BOM-2.23ea5](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea5)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea2](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea2), [BOM-2.23ea6](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea6)
