### ISSUE TITLE
Support anchors in Yaml parser

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Wire#413]
We should support reading and deserializing anchors from YAML, such as in example 10.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea3](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea3), [BOM-2.23ea16](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea16)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea3](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea3), [BOM-2.23ea17](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea17)
