### ISSUE TITLE
VanillaMessageHistory.hashCode() doesn't behave as expected

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#415]
While you probably should be using `VanillaMessageHistory` as a key or in a key, it should still behave sensibly.
If you have a field that is a `VanillaMessageHistory` consider making it `transient`

The data structure is unusual in that it records every time it is read and written to support tracing. i.e. writing it alters it.

In this issue, it has special handling for `HashWire`

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea3](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea3), [BOM-2.23ea16](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea16)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea3](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea3), [BOM-2.23ea17](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea17)
