### ISSUE TITLE
Add WireCommon.isBinary()

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#418]
Instead of calls like `wire instanceof BinaryWire`

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea3](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea3), [BOM-2.23ea16](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea16)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea3](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea3), [BOM-2.23ea17](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea17)
