### ISSUE TITLE
Enhance documents on project main page

### ISSUE THREAD

**Issue by loveyoupeng** [OpenHFT/Chronicle-Wire#42]
Could you improvement the doc on the project main page, there are some typo and ambiguous descriptions, which is hard to understand. And could you provide some design descriptions to help people to evaluate if it is a fit.

**Comment by peter-lawrey** [comment]
I have asked Catherine to review.
Can you clarify which design points you are looking for?

Wire is a wrapper for Bytes. 
It add a format e.g. JSON, YAML, Binary to Bytes which is an enhancement of ByteBuffer.
When you call a method on Wire, it calls the appropriate method on Bytes which does this for the format chosen.

**Comment by loveyoupeng** [comment]
Thanks for the attention. 
Yes as you mentioned that it is a wrapper for bytes. Probably you could list some statement regarding to best use cases such as easy API to handle bytebuff. And the pros cons as well.
One more suggestions is could you also share the high level relationships between all the pieces of the projects under openhft umbrella. 
Some of them are in different development cycles, if I cherry pick some of them. What's the strategy you suggest to maintain version upgrade

**Comment by peter-lawrey** [comment]
Ok. We can try to make this clearer

**Comment by peter-lawrey** [comment]
We have added a table of contents. We have details comparison with other serialisation libraries. We support ByteBuffer interop. 
Chronicle Wire uses Chronicle Bytes for bytes manipulation and Chronicle Core for low level JVM access.

Wire handles
- adding and removing fields.
- changing the order of fields.
- changing the type of a field.
- aliases for types so you can change them.

**Comment by loveyoupeng** [comment]
Great thanks a lot

Thanks a lot
Yunpeng Li

**Comment by peter-lawrey** [comment]
Are there products you are comparing which had documentation you think we could emulate?

**Comment by loveyoupeng** [comment]
actually I'm comparing binary protocols such as avro protobuff, currently we highly relay on json/xml based http protocol between internal services, which is a waste of resources given the message is complex object tree.
in terms of the doc, could you adding some introduction section to the concepts/metaphor used in Chronicle-Wire, such as what is DocumentContext, WireIn ValueIn and their relationships. seems Chronicle contains a few terms and metaphor from finance industry, it is a little hard to understand vanilla means normal/default for people not from the industry :P

**Comment by peter-lawrey** [comment]
To start with, I suggest you start with the generic use Marshallable and
MarshallableIn/Out interface.

We have a lower level interface where you control exactly how serialization
/ deserialization works. A lower level interface where you can work at the
byte/primitive level and lastly an interface where you can get a raw native
memory address and do what you want. Eg exchange data direct with a GPU.

You shouldn't need to understand the whole library to use it or we have
done something wrong.

**Comment by benwimpory** [comment]
I found these 2015 blog posts and the wire unit tests a good introduction.

http://www.rationaljava.com/2015/10/chronicle-wire-tutorial-next-level-in.html?m=1

**Comment by loveyoupeng** [comment]
Great, thanks for the advices

Thanks a lot
Yunpeng Li

On Apr 4, 2017 4:21 PM, "benwimpory" <notifications@github.com> wrote:

I found these 2015 blog posts and the wire unit tests a good introduction.

http://www.rationaljava.com/2015/10/chronicle-wire-
tutorial-next-level-in.html?m=1

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenHFT/Chronicle-Wire/issues/42#issuecomment-291428499>,
or mute the thread

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
