### ISSUE TITLE
Added MarshallableOutBuilder for file/http protocols

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#423]
fyi @RobAustin

**Comment by peter-lawrey** [comment]
Please see an example as a starting point for HTTP.
Need to add a test that connects to the built in Java HTTP server in test.
Also add a simple JLBH benchmark

**Comment by peter-lawrey** [comment]
Example of a simple HTTP server https://dzone.com/articles/simple-http-server-in-java

**Comment by RobAustin** [comment]
@peter-lawrey  - rather than writing more code for this why don't you just use the queue web gateway?

**Comment by peter-lawrey** [comment]
The main features are;
- Supports multiple wire types
- Supports the MethodWriters
- Works using Java 8 builtin libraries
- Is entirely open source.

**Comment by RobAustin** [comment]
closing as this has mostly been addressed by https://github.com/ChronicleEnterprise/Chronicle-Services-Demo/blob/main/GettingStarted/Example10/README.adoc
