### ISSUE TITLE
VanillaMethodWriterBuilder.CallSupplierInvocationHandler should be static

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Wire#426]
`CallSupplierInvocationHandler` holds a reference to its outer class instance which is rather extensive.  It is better to provide the limited parameters needed explicitly in the constructor.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea4](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea4), [BOM-2.23ea25](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea25)
