### ISSUE TITLE
Allow dumping EventGroup with marshalling

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#429]
c.f. https://github.com/ChronicleEnterprise/Chronicle-Services/issues/264

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea4](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea4), [BOM-2.23ea25](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea25)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea9](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea9), [BOM-2.23ea44](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea44)
