### ISSUE TITLE
It is possible to deepCopy() an enum value

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Wire#441]
For a simple enum value, the resulting object has null name.

For an anonymous subclass enum value, the resulting object has correct name but is not `==` the actual correct enum value singleton.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea9](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea9), [BOM-2.23ea44](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea44)
