### ISSUE TITLE
Return a better value for DocumentContext::index

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Wire#442]
Most classes return 0 which is a valid index.  There are several better opportunities:

A) return the read position of the start of the excerpt
B) return -1

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea23](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea23), [BOM-2.23ea80](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea80)
