### ISSUE TITLE
ValueOut lacks JavaDoc

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Wire#443]
The interface `net.openhft.chronicle.wire.ValueOut` does not have JavaDocs as it should.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.24ea5](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.24ea5), [BOM-2.24ea17](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea17)
