### ISSUE TITLE
ValueIn lacks JavaDoc

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Wire#444]
The interface `net.openhft.chronicle.wire.ValueIn` does not have JavaDocs as it should.

**Comment by RobAustin** [comment]
see https://github.com/OpenHFT/Chronicle-Wire/pull/798

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.25ea5](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.25ea5), [BOM-2.25ea23](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25ea23)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.25ea10](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.25ea10), [BOM-2.25ea30](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25ea30)
