### ISSUE TITLE
Implement net.openhft.chronicle.wire.WireIn#copyTo

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Wire#446]
WireIn#copyTo is missing full implemenations for:

 
- JSON Wire
- Text Wire
- YAML Wire
 

This functionality is required to convert JSON messages into binary so that they can be written to a Chronicle Queue as Binary Wire.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea9](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea9), [BOM-2.23ea44](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea44)
