### ISSUE TITLE
Reduce SQ Issues

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Wire#453]
The quality gate is not passed any longer:

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/7457876/167149701-82547f05-3625-40c3-bbdc-e5fbabd62071.png">

**Comment by JerryShea** [comment]
@minborg I think this was always this high, it is just showing up because we have fixed up the Sonar builds. I'll just increase the number now (to 728) as I have a few PRs to get through, and we can ratchet it down.

**Comment by minborg** [comment]
That is good but I think we should reopen the issue.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea9](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea9), [BOM-2.23ea44](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea44)
