### ISSUE TITLE
JsonWire : serialising a DTO the number of '{' and '}' should be equal

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Wire#467]
issue addded to branch 'issue/467', as  Chronicle-Wire/src/test/java/net/openhft/chronicle/wire/TestJsonIssue467.java

see commit https://github.com/OpenHFT/Chronicle-Wire/commit/78af4075f0e52be95921f746a5ca3ddc40b1b2fa

**Comment by peter-lawrey** [comment]
The logic for checking whether to trim a white space is wrong.
