### ISSUE TITLE
Remove addPadding(true) for useTextDocuments()

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#471]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea13](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea13), [BOM-2.23ea68](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea68)
