### ISSUE TITLE
AbtractMarshallable to use properties vs fields

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Wire#48]
AbstractMarshallable and net.openhft.chronicle.wire.WireMarshaller#readMarshallable etc. read and write direct from fields and don't use properties.
This issue a placeholder to investigate the performance impact etc. of allowing properties to be used in preference to fields.

**Comment by RobAustin** [comment]
@JerryShea please work on this or close this issue - thanks.

**Comment by RobAustin** [comment]
closed as its just a place holder
