### ISSUE TITLE
SerializableObjectTest is flappy

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Wire#482]
This could be a genuine bug. The error is:
```
org.junit.ComparisonFailure: expected:<[2,[ 1, ]3]> but was:<[2,[1,]3]>
Expected :[2, 1, 3]
Actual   :[2,1,3]
```
When you attach a debugger to it, the LHS (source) is a LinkedList containing integers 2, 1, 3 and the RHS (target) is an ArrayList with a single string element `2,1,3`

Oddly this behaviour seems non-deterministic, the test sometimes passes and sometimes fails.

**Comment by nicktindall** [comment]
I suspect this test never ran under the old surefire. See the test history, it only starts running on 27/5 after the parent POM upgrade (which upgraded to surefire 3.0.0-M6) 
https://teamcity.chronicle.software/test/-2175485830732454387?currentProjectId=Chronicle_ChronicleWire&expandTestHistoryChartSection=true

**Comment by RobAustin** [comment]
@nicktindall this has had a few commits... can it now be closed ?

**Comment by nicktindall** [comment]
@RobAustin No there's actually been no work done on this, I think the "few commits" might just be my original ignore commits (there's two because I incorrectly did it using the JUnit 4 annotation on my first attempt) being pushed/cherry-picked to different branches.
