### ISSUE TITLE
Improve documentation for MethodReaders/Writers

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Wire#489]
These are [mentioned in the docs](https://github.com/OpenHFT/Chronicle-Wire#example-with-methodreaders), but not explained at a high level together with their benefits (not least ease of use).

We should at least link to some simpler examples of how to use them e.g. https://vanilla-java.github.io/tag/Microservices/ e.g. https://vanilla-java.github.io/2016/03/23/Microservices-in-the-Chronicle-world-Part-1.html (this article is a bit out of date but captures the simplicity nicely).

There are also examples at https://github.com/OpenHFT/Chronicle-Queue-Demo/

**Comment by RobAustin** [comment]
for another example also see - https://dzone.com/articles/java-how-to-leverage-method-chaining-to-add-smart

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea38](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea38), [BOM-2.23ea121](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea121)
