### ISSUE TITLE
Builds fail on Zing

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Wire#494]
<img width="468" alt="image" src="https://user-images.githubusercontent.com/7457876/173097000-dd1bb7fd-896a-4026-b6a8-2f2d5df4df2b.png">

**Comment by RobAustin** [comment]
closing as currently working 

![image](https://user-images.githubusercontent.com/6506056/189594791-7a96410d-5949-4925-8360-15c18b573581.png)
