### ISSUE TITLE
Create test example for article on LongConverters

### ISSUE THREAD

**Issue by j4sm1ne96** [OpenHFT/Chronicle-Wire#498]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea14](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea14), [BOM-2.23ea70](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea70)
