### ISSUE TITLE
If a field has an enum value but the class isn't known, you get a strange error message.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#50]
e.g.

```yaml
enumField: !UnknownEnum VALUE
```

reports, Unexpected character `V`.  It could instead report, unknown class `UnknownEnum`

**Comment by epickrram** [comment]
Fixed for TextWire, BinaryWire interprets unknown types as text data, so this doesn't really apply there.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
