### ISSUE TITLE
Make net.openhft.chronicle.wire.AbstractMarshallable implement net.openhft.chronicle.bytes.BytesMarshallable

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Wire#51]

**Comment by epickrram** [comment]
Requirement: Map should accept AbstractMarshallable keys/values.

**Comment by epickrram** [comment]
Updated Map & tested AbstractMarshallable key/value components.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
