### ISSUE TITLE
Fix @Ignore on YamlWireTest ( in Chronicle-Wire )

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Wire#510]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea23](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea23), [BOM-2.23ea80](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea80)
