### ISSUE TITLE
Pass comments from in.yaml to out.yaml to improve documentation

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#513]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea21](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea21), [BOM-2.23ea75](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea75)
