### ISSUE TITLE
Make MarshallableOut.methodWriterBuilder easier to override

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#517]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea23](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea23), [BOM-2.23ea80](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea80)
