### ISSUE TITLE
net.openhft.chronicle.wire.WireIn#copyTo does not work as expected text<->binary

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Wire#52]
See net.openhft.chronicle.wire.CopyTest

**Comment by peter-lawrey** [comment]
I have updated the test. There was a bug for Binary -> Text and Text ->
Binary is not support yet, so left this issue open for now.
ᐧ

**Comment by dpisklov** [comment]
We currently do not support copy from text to non-text wire, and that's not something we or our clients require. We will close this issue for now, and in the future if the requirement arises from the client of ours, we will implement this.
