### ISSUE TITLE
Problems de/serialising AbstractMarshallableCfg with collections of strings

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Wire#522]
Due to missing `net.openhft.chronicle.wire.WireMarshaller.StringCollectionFieldAccess#copy`, the collection of strings was being copied as an object rather than a collection.

Symptoms:
* collection of Strings not showing up in `toString()`
* collection of Strings not being serialised from DTO to the Wire

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea22](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea22), [BOM-2.23ea76](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea76)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.22.20](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.22.20), [BOM-2.22.142](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22.142)
