### ISSUE TITLE
Allow object keys in key-value mappings

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Wire#525]
See for example `net.openhft.chronicle.wire.YamlWireTest#testMapReadAndWriteMarshable` - split from #510

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea30](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea30), [BOM-2.23ea104](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea104)
