### ISSUE TITLE
Normalise return characters in YamlTester under windows

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#535]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea25](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea25), [BOM-2.23ea90](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea90)
