### ISSUE TITLE
BinaryWire.readText to skip padding rather than return null

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#539]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea26](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea26), [BOM-2.23ea91](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea91)
