### ISSUE TITLE
How to encode decode BigDecimal

### ISSUE THREAD

**Issue by loveyoupeng** [OpenHFT/Chronicle-Wire#54]
Hi there ,
       Any suggestions how to deal with BigDecimal, since our existing code base are highly rely on it to represent financial data

**Comment by epickrram** [comment]
You could either serialise the `toPlainString()` result and use `new BigDecimal(String)` to deserialise, or convert `BigDecimal` to a `BigInteger` and `int` `scale` and use `new BigDecimal(BigInteger, int scale)` to deserialise.

**Comment by loveyoupeng** [comment]
thanks for your suggestions, I will look into it.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
