### ISSUE TITLE
Add WireOut.writingIsComplete() to check if a wire is writing a chained method

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#540]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea27](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea27), [BOM-2.23ea92](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea92)
