### ISSUE TITLE
Added Channels for remote access to gateways

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#545]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23ea30](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23ea30), [BOM-2.23ea104](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea104)
