### ISSUE TITLE
Add support for filtering methods in MethodReader by content

### ISSUE THREAD

**Issue by peter-xch** [OpenHFT/Chronicle-Wire#55]

**Comment by peter-lawrey** [comment]
Add an interface MethodFilterOnFirstArg to support filtering on MethodReading.

**Comment by RobAustin** [comment]
thanks peter

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
