### ISSUE TITLE
Fix doco "Write a message with a thread-safe size prefix"

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Wire#578]
https://github.com/OpenHFT/Chronicle-Wire/#write-a-message-with-a-thread-safe-size-prefix is inaccurate

Wire used to support this, but it does not any more. The diagram is useful, and the commentary around the length field, but we need to completely re-write the section and take out any mention of thread safety.

**Comment by peter-lawrey** [comment]
Can you clarify what you believe isn't supported? Not all these features are used by queue however, wire still supports or should support it. If this is broken we should create a unit test showing what is broken and fix it.

**Comment by JerryShea** [comment]
The premise of that section is incorrect. I am sure that Wire _used_ to have a thread-safe prefix but it does not any more - it has a prefix still but there is no exclusion provided by it.

The comment in the example code
```
// writeDocument() blocks other readers and writers, until the writing of this
// data is completed. See the above comment.
```
is not correct - writeDocument does not block other readers and writers. 

My understanding from a conversation with @peter-lawrey is that we no longer require this functionality in Wire. Queue provides this functionality when wrapping Wire and using an alternative mechanism.

The documentation needs to be re-titled and re-written but there is still some good value in it - the diagram is useful, and the commentary around the length field, but we need to completely re-write the section and take out any mention of thread safety.

**Comment by peter-lawrey** [comment]
Updates/removed these reference in this PR https://github.com/OpenHFT/Chronicle-Wire/pull/754
