### ISSUE TITLE
Update Figure 1 in the readme to use the new style

### ISSUE THREAD

**Issue by foroughgoudarzi** [OpenHFT/Chronicle-Wire#596]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.24ea5](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.24ea5), [BOM-2.24ea17](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea17)
