### ISSUE TITLE
Field name collision between method arguments and exception names

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Wire#598]
Causing tests such as `net.openhft.chronicle.map.channel.MapHandlerTest` to produce warnings:
```
/net/openhft/chronicle/map/channel/MapHandlerTestReplyTextMethodWriter.java:60: error: variable t is already defined in method reply(net.openhft.chronicle.map.channel.MapHandlerTest.DTO)
            }catch (Throwable t) {
                              ^
```

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.24ea5](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.24ea5), [BOM-2.24ea17](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea17)
