### ISSUE TITLE
Don't use Proxy classes in the name of generated classes

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#606]
In MethodReaders, the name of the implementing class is used.
However, for proxy classes, the name can be reused if the earlier instance of the classes is cleaned up.
This only occurs after a GC cleans up an earlier proxy and reuses that name.

Instead, the implementing interface should be used rather than the proxy.

**Comment by JerryShea** [comment]
@peter-lawrey I believe this is complete now. Please re-open if not

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.24ea6](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.24ea6), [BOM-2.24ea38](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea38)
