### ISSUE TITLE
Support storage of data in lower 30 bits of header while it is being written to

### ISSUE THREAD

**Issue by epickrram** [OpenHFT/Chronicle-Wire#61]
https://github.com/OpenHFT/Chronicle-Queue/issues/415

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
