### ISSUE TITLE
Don't allow enterHeader to overwrite EOF

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Wire#618]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.24ea8](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.24ea8), [BOM-2.24ea40](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea40)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23.42](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23.42), [BOM-2.23.157](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.157)
