### ISSUE TITLE
Resolve methodIds when parsing

### ISSUE THREAD

**Issue by gordonnb** [OpenHFT/Chronicle-Wire#62]
VanillaWireParser was not recognising method names when encoded as MethodId integers.  This resulted in debug messages like:

Unknown method-name='1' from 25 at ...

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
