### ISSUE TITLE
Compression not working due to asymmetric write/read 

### ISSUE THREAD

**Issue by joncrocks** [OpenHFT/Chronicle-Wire#63]
I have been using Chronicle-Queue and was investigating the compression offered by COMPRESSED_BINARY in WireType.

Unfortunately while I was eventually able to get compression to apply (as not all interactions with an ExcerptAppender seemed to trigger compression), decompression did not.

I can see that the tests for compression/decompression are @Ignored, which is frustrating given the availability of COMPRESSED_BINARY. From the Chronicle-Queue project you can therefore create a queue with a WireType that doesn't work correctly. It might be that it works OK for write/read of text, but I was trying to write/read bytes.

Having debugged this (as it was not clear why it wasn't working, no comments/warnings etc.), I can offer what I think is the issue.

There's a couple of places that look like they're all suffering from the same class of issue. e.g. in WireIn#bytes, the first thing that is done is a call to readLength(). Unfortunately it seems that if our code is TYPE_PREFIX (and some of the other codes), there is a side-effect that the read pointer is increment past the code, stop bit and the compression details.

When we return to bytes(...) and do a readCode(), the code we get is U8_ARRAY, which is the type code that is written for the underlying compressed bytes when we perform compression. What should happen is that readCode gives us TYPE_PREFIX and then we decompress the bytes.

Having looked at the code I think a fix might be to only call getLength() after we have peeked and determined the code or only calling it when we have U8_ARRAY (as the length of the compressed data is unlikely to be very useful to us, we're about to decompress it).

**Comment by RobAustin** [comment]
@joncrocks thanks for your investigation on this, are you able to offer a fix to this as a pull request. If you are able to we will merge it into the code base.

**Comment by dpisklov** [comment]
I have enabled tests for COMPRESSED_BINARY and they all pass. I'm going to close this assuming it was fixed. If it's still an issue please provide a failing test and reopen

**Comment by joncrocks** [comment]
I believe the test in net.openhft.chronicle.wire.BinaryWire2Test.testCompression() was the test that failed/was @Ignore. Re-running it still gives me a fail.

**Comment by dpisklov** [comment]
@joncrocks that test was testing some internal stuff. I changed it to test the actualy functionality and it works.
The only test that doesn't work at the moment is the one using Snappy compression - for some reason it's not being uncompressed and throws pretty cryptic error, so I'm going to drop support for snappy. gzip and lzw work fine, as you can see in tests.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
