### ISSUE TITLE
Improve support for !!binary in YAML wire

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Wire#633]
see #509

The relevant is test is `BinaryInTextTest`

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.24ea21](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.24ea21), [BOM-2.24ea65](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea65)
