### ISSUE TITLE
ThreadLocal poisoning of STRICT_ESCAPED_END_OF_TEXT

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Wire#638]
If a JSON was parsed in the current thread, then STRICT_ESCAPED_END_OF_TEXT will contain STRICT_END_OF_TEXT_JSON_ESCAPING, and subsequent parsing of TEXT wire will fail with mysterious errors such as "parser stuck".

Perhaps vice versa.

These TLs are used for caching so they should overwrite TL if an incorrect object is found inside.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.24ea12](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.24ea12), [BOM-2.24ea47](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea47)
