### ISSUE TITLE
Method writers that implement a lot of interfaces sometimes have an impossibly long filename

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Wire#643]
e.g. `AllOut2OrderRequestListenerHeartbeatSourceHeartbeatDefinitionsListenerMarketDataUpdateListenerMidListenerNewOrderSingleListenerOmsHedgerTradeListenerOpenOrdersListenerPaidGivenTickListenerPeriodicUpdateSourcePositionAdjustmentsListenerPositionServerConfigListenerCalculationLogListenerResetAllPositionsListenerSignalDataListenerPositionListenerStatusListenerConfigOutPricerOutDebuggableApplicationInfoListenerApplicationErrorListenerLadderByQtyListenerLadderByRateListenerHeartbeatListenerHeartbeatErrorListenerHedgerControlListenerExecutionReportListenerEcommTradeListenerEquivalentPositionsListenerDropCopyTradeListenerDropCopyTradeMissingAlertListenerOrderExecutionReportListenereventInterceptingTextMethodWriter`

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23.43](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23.43), [BOM-2.23.163](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.163)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.24ea12](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.24ea12), [BOM-2.24ea47](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea47)
