### ISSUE TITLE
There's no way to encode a "zero" value in the SymbolsLongConverters

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Wire#649]
We take numeric zero to mean empty string which means strings that consist entirely of the "zero" character can't be round-tripped.

e.g. the following both fail
`assertEquals(Base85LongConverter.INSTANCE.asText(Base85LongConverter.INSTANCE.parse("0")), "0");`
`assertEquals(Base85LongConverter.INSTANCE.asText(Base85LongConverter.INSTANCE.parse("00000")), "00000");`

a similar problem exists for values with leading "zero" values e.g.
`assertEquals(Base85LongConverter.INSTANCE.asText(Base85LongConverter.INSTANCE.parse("00012")), "00012");`

Not sure if this is a bug, or just a limitation to be aware of when using them to encode strings. Perhaps it's something we need to be explicit about in our docs?

**Comment by nicktindall** [comment]
When fixing this it broke an existing test that confirms the empty string round-trips correctly (i.e. `converter.asText(converter.parse("")).equals("")`)

I don't think we should expect that to round-trip correctly. `Integer.parseInt("", 16)` throws a NumberFormatException. I don't think we should do that, but I don't think we should spit out an empty string for zero.

**Comment by nicktindall** [comment]
This is necessary so that we have a way to encode empty strings. Closing.

**Comment by nicktindall** [comment]
On second thoughts it does present an issue because it means there's no way to encode a solitary "zero" value.

e.g. For Base85LongConverter, the following fails
`assertEquals(Base85LongConverter.INSTANCE.asText(Base85LongConverter.INSTANCE.parse("0")), "0");`

**Comment by yevgenp** [comment]
I don't think it's a bug. It's by design rather.
Since we are doing `String -> long -> String` conversion and numerical types don't preserve leading zeros (i.e. `Long.parseLong("12") == Long.parseLong("00012")` ).
I believe this issue should be closed. @nicktindall ?

**Comment by nicktindall** [comment]
> I don't think it's a bug. It's by design rather.
> Since we are doing `String -> long -> String` conversion and numerical types don't preserve leading zeros (i.e. `Long.parseLong("12") == Long.parseLong("00012")` ).
> I believe this issue should be closed. @nicktindall ?

No, we promote it as an efficient way to encode strings, the examples I've seen show the encoding used to encode a symbol in a message. It would not be expected that a method of encoding strings was lossy, e.g. In the case of https://www.londonstockexchange.com/market-stock/0LMO/vanguard-ftse-all-world-ex-us-index/overview

Which would end up being LMO after a round trip.

I think at very least we need to mention this in the documentation for the feature. @yevgenp

**Comment by yevgenp** [comment]
I've added a possible implementation in the above PR (incomplete). It obviously comes with other tradeoffs. 
I'd like @peter-lawrey 's opinion if it's worth the effort.

**Comment by peter-lawrey** [comment]
It definitely should be documented that leading zeros are truncated. For the Vangard use case, there is more appropriate encoding.

**Comment by nicktindall** [comment]
This has been address by https://github.com/OpenHFT/Chronicle-Wire/pull/822, uses of `@Base85` should be replaced with `@ShortText` in demos/docs.
