### ISSUE TITLE
Added meta data ignore list for methodReader

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Wire#66]
please ignore the following files when they are meta data "header", "index", "index2index", "roll"

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
