### ISSUE TITLE
Add support so the method reader, so that it skips over meta messages generated from TimedStoreRecovery#recoverAndWriteHeader

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Wire#67]
Make a change to chronicle queue so that it uses an event name when writing the TimedStoreRecovery#recoverAndWriteHeader message. ( currently it does not do this ), then in the methodReader skip over this message, as the current code will crash if it encounters the TimedStoreRecovery.

**Comment by RobAustin** [comment]
I'm going to close this as I don't feel it's required any more

**Comment by hft-team-city** [comment]
Released in Chronicle-Wire-2.17.5 (https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.5), BOM-2.17.30 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.30)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
