### ISSUE TITLE
deepCopy fails when copying DTOs with @AsMarshallable dynamic enum fields

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Wire#683]
It results in an invalid re-use pattern of the shared `Wires.acquireBinaryWire()`

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.24ea27](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.24ea27), [BOM-2.24ea86](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea86)
