### ISSUE TITLE
Changed history message to use writeEventName

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Wire#69]
Changed history message to use writeEventName, to bring it inline with other places that the history message is written, as this makes it easier to detect if the history message is written using a custom bytes marshaller or wire. If its written with an event name, when we come to read it, we can safely assume, that it was written with wire.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
