### ISSUE TITLE
Fix Issue #272 never merged

### ISSUE THREAD

**Issue by gregallen** [OpenHFT/Chronicle-Wire#701]
Seems this fix is not on neither the ea branch nor the 2.23 release branch. Can it be merged or cherry picked?

**Comment by gregallen** [comment]
See c36a105

**Comment by JerryShea** [comment]
@peter-lawrey assigning to you so you as was your change originally.

@gregallen have you run into the same problem as described in the original issue - #272 ?

**Comment by gregallen** [comment]
Yes - i reproduced it with a parameterised test that tested read/write marshall roundtrip against variety of wire-types.

broke for YamlWire on a int[] field

**Comment by JerryShea** [comment]
@gregallen that test is in the mainline - added by https://github.com/OpenHFT/Chronicle-Wire/commit/f795fb21cb0a0eb0bc42f3cea6daaa3bf2c3dd23
