### ISSUE TITLE
Created a NOP FieldNumberParselet to replace the use of NULL

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Wire#71]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
