### ISSUE TITLE
Removed redundant methodId lookup

### ISSUE THREAD

**Issue by gordonnb** [OpenHFT/Chronicle-Wire#72]
MethodIds are now encoded as field numbers.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
