### ISSUE TITLE
WireParser has a NO_OP parser which doesn't do anything.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#73]
The requirement is to skip the entry, rather than not do anything.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
