### ISSUE TITLE
reset() should handle mutable fields, especially collections and marshallables

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Wire#732]
```
public static void main(String[] args) {
    ExecutionReportDto or1 = new ExecutionReportDto();
    ExecutionReportDto or2 = new ExecutionReportDto();
    Jvm.warn().on(Main.class, String.format("Before reset: %s == %s is %s", or1.clientIdentifier(), or2.clientIdentifier(), or1.clientIdentifier() == or2.clientIdentifier()));

    or1.reset();
    or1.clientIdentifier().clientId("foo");
    Jvm.warn().on(Main.class, String.format("After reset first: %s == %s is %s", or1.clientIdentifier(), or2.clientIdentifier(), or1.clientIdentifier() == or2.clientIdentifier()));

    or2.reset();
    or2.clientIdentifier().requestId("bar");
    Jvm.warn().on(Main.class, String.format("After reset second %s == %s is %s", or1.clientIdentifier(), or2.clientIdentifier(), or1.clientIdentifier() == or2.clientIdentifier()));
    Jvm.park();
}
```

leads to the output:

```
Before reset: ClientIdentifierDto{clientId='null', requestId='null'} == ClientIdentifierDto{clientId='null', requestId='null'} is false
After reset first: ClientIdentifierDto{clientId='foo', requestId='null'} == ClientIdentifierDto{clientId='null', requestId='null'} is false
After reset second ClientIdentifierDto{clientId='foo', requestId='bar'} == ClientIdentifierDto{clientId='foo', requestId='bar'} is true 
```

So `reset()` doesn't really clear the fields of internal objects. It will only work for immutable objects, but not for `SelfDescribingMarshallable` fields. State from one execution report is getting into the second execution report, and even if there was just one instance of `ExecutionReport` it would still fail to reset.

How I imagine this should work:
- For primitive and immutable type fields, replace the value/reference to cached initial value.
- For collections, issue `clear()`. Alternatively, do a `deepCopy(cachedInitialValue, value)`.
- For `SelfDescribingMarshallable`s (and perhaps other kinds of marshallables), issue `reset()`. Alternatively, do a deep copy of cached initial value

But the approach is to be discussed.

**Comment by maxim-ponomarev** [comment]
I vote for deepCopy() of cached initial object (for SelfDescribingMarshallable or even for  Marshallable's).
Just reseting the the object will be un-intuitive and will change current behaviour dramatically.

**Comment by alamar** [comment]
@maxim-ponomarev I think that nested `reset()` is appropriate because it will itself copy all of its fields from intial object.

**Comment by peter-lawrey** [comment]
`reset()` is called often so it is better to not deep copy data if we can. Better to leave it in the state it had before it has ever been used. ie same as creating a new one.
