### ISSUE TITLE
StoreWritingProcessInHeaderTest fails if other tests are run first.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#74]
Wires.ENCODE_TID_IN_HEADER needs to be set for this test, however it's value can be set to false before the test is run.

The test runs by itself but fails if Wires is initialised first.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
