### ISSUE TITLE
Rename WireType.BINARY (and BINARY_LIGHT) to reflect the fact that BINARY_LIGHT is for binary encoding and BINARY is for DELTA and BINARY support

### ISSUE THREAD

**Issue by dpisklov** [OpenHFT/Chronicle-Wire#78]
Will just add a javadoc for now, but we need to rename it later when we are ready for breaking change

**Comment by RobAustin** [comment]
@dpisklov I disagree - I think the names are fine, BINARY is for BINARY delta is a form of BINARY wire and you should be able to read Delta without having to change your wire format. If you don't want this then use the BINARY_LIGHT format, which as its name implies is a lighter form of binary. It's just not worth the interruption and cost of changing it.
