### ISSUE TITLE
VanillaMethodReader calls a ThreadLocal.get() many times but is single threaded

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#79]
This is showing up as expensive in a flame graph.

**Comment by peter-lawrey** [comment]
Tested in Chronicle-Services

**Comment by hft-team-city** [comment]
Released in Chronicle-Wire-1.12.4 (https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-1.12.4), BOM-1.15.271 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.271)

**Comment by hft-team-city** [comment]
Released in Chronicle-Wire-1.12.4 (https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-1.12.4), BOM-1.15.272 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.272)

**Comment by hft-team-city** [comment]
Released in Chronicle-Wire-1.12.4 (https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-1.12.4), BOM-1.15.274 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.274)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
