### ISSUE TITLE
JSONWire incorrectly handles nested collections

### ISSUE THREAD

**Issue by maxim-ponomarev** [OpenHFT/Chronicle-Wire#797]
Reproduced in branch `797-JSONWire-incorrectly-handles-nested-collections`

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.25ea8](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.25ea8), [BOM-2.25ea23](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25ea23)
