### ISSUE TITLE
Persist WireIn msgs to ChronicleQueue

### ISSUE THREAD

**Issue by davidjones7076** [OpenHFT/Chronicle-Wire#8]
Hi - I was thinking of writing an extension to TcpWireHandler to receive serialised objects which are then persisted to a Chronicle Queue.

Is there any recommended way to persist the message to the queue in this case ?  I am keen to avoid serialising the object again as presumably the WireIn object has access to the underlying bytes.

Thanks,

David

**Comment by peter-lawrey** [comment]
Unfortunately you cant just pass the Chronicle Bytes to Queue which uses
Java lang. There us some bridging code which uses the address and the
length to avoid over head.
The real answer is to use Chronicle Queue v4 but it's so Alpha it's not
even building at the moment.

In short you need to use the underlying memory address. I would look it up
now except I need to sleep.

Peter.

**Comment by davidjones7076** [comment]
Makes sense.  At least I wasn't missing something obvious!

I think the call to myObject.read(inWire) call clears the underlying byte buffer, or certainly moves the position/limit pointers, so I suspect the raw bytes I want to persist will need to be acquired before making the call to read(Wire).

I'll carry on looking into the Chronicle-Bytes/Core code to see what the appropriate call would be to get these bytes into a byte[].

**Comment by peter-lawrey** [comment]
From Bytes you can do read(byte[]) or write(byte[]).  There is only a trick
if you want to copy from Wire to Queue without using a byte[].

**Comment by davidjones7076** [comment]
Ah ok.  I assumed I'd have to do the copy to a byte[] in order to do the write to the queue, but it sounds like this trick would avoid the copy overhead completely ?  I'd appreciate it if you could publish it if this is the case.

**Comment by peter-lawrey** [comment]
The most efficient would be to use the try-with-resource method

    byte[] byteArray = ....
    try (DocumentContect dc = appender.writingDocument()) {
         dc.wire().bytes().write(byteArray);
    }

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
