### ISSUE TITLE
Add tests for errors you can get in configuration files

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#80]

**Comment by hft-team-city** [comment]
Released in Chronicle-Wire-2.17.5 (https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.17.5), BOM-2.17.30 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.30)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
