### ISSUE TITLE
Support custom ClassLookup in WireTypeConverter

### ISSUE THREAD

**Issue by maxim-ponomarev** [OpenHFT/Chronicle-Wire#806]

**Comment by RobAustin** [comment]
@Peter we had a meeting regarding this and you suggested using Tuples, I think the tuples are enabled through a static and you thought that it would be better to set it via a local property, ( as currently we feel it may effect all wire instance ) -  we have a failing test that you said that you would fix, this issues is currently blocking work on the services UI

**Comment by tgd** [comment]
I've asked Yevgen to run with this - thanks Yevgen :+1:
