### ISSUE TITLE
Added bitset support

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Wire#82]
Optimise  the way bit sets are serialised and de-serialized with wire, so that the following would be handled better:

```
class Dto {
java.util.BitSet mybitset;
}
```

**Comment by hft-team-city** [comment]
Released in Chronicle-Wire-1.16.13 (https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-1.16.13), BOM-1.16.125 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.125)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
