### ISSUE TITLE
Added to the Documentation more details on the subset of YAML we support

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Wire#83]
We don't currently support the whole of yaml, so take spec of YAML, document the bits we do support and highlight the parts we don't, some parts of the spec are ambiguous and should explain how we handle those situations.

For example:
In the spec its says that if you add a single ! then this is an application specific type, but then does not go on to say what this means.

Other things
-------------
- plugin for intellij idea
- yaml schema

**Comment by RobAustin** [comment]
see https://github.com/OpenHFT/Chronicle-Wire#yaml-2-features-currently-suppored-in-chronicle-wire

**Comment by hft-team-city** [comment]
Released in Chronicle-Wire-1.16.13 (https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-1.16.13), BOM-1.16.125 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.125)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
