### ISSUE TITLE
Add sub-sequence parse() to LongConverter

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Wire#835]
> parseSubSequence(CharSequence sequence, int from, int to)

To avoid creating extra garbage when working with partially parsed input.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.25ea10](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.25ea10), [BOM-2.25ea30](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25ea30)
