### ISSUE TITLE
Wire does not use overridden ClassLookup for Classes

### ISSUE THREAD

**Issue by maxim-ponomarev** [OpenHFT/Chronicle-Wire#840]
Reproduced in `net.openhft.chronicle.wire.ClassAliasPool840Test#typedMarshallableUsesCustomClassLookup` in `#840-Reproduce-issue-typedMarshallable()-ignores-custom-ClassLookup`

**Comment by peter-lawrey** [comment]
Fixed in PR #845

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.25ea10](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.25ea10), [BOM-2.25ea30](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25ea30)
