### ISSUE TITLE
Flatten the call stack for Method Readers

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#841]

**Comment by peter-lawrey** [comment]
Fixed in PR #842

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.25ea10](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.25ea10), [BOM-2.25ea30](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25ea30)
