### ISSUE TITLE
BinaryWire.text(CharSequence) with long strings inefficiently calls findUtf8Length() twice

### ISSUE THREAD

**Issue by gregallen** [OpenHFT/Chronicle-Wire#848]
Owing to the check for the concise representation of strings less than 32 utf-8 chars, the length check is called once in text() and once from CommonMappedBytes.writeUtf8()

This becomes expensive for long strings

A simple optimisation is to rely on CharSequence.length() as a pre-check - if CharSequence.length > 0x20 then there is no need to call findUtf8Length() in the first case.

**Comment by tgd** [comment]
Thanks for flagging @gregallen - we will take a look.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.24.30](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.24.30), [BOM-2.24.113](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24.113)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23.50](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23.50), [BOM-2.23.218](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.218)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.25ea11](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.25ea11), [BOM-2.25ea37](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25ea37)
