### ISSUE TITLE
fixed readOne() so that when reading meta data, will now skip to next message, if current eventName is ignored

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Wire#86]

**Comment by hft-team-city** [comment]
Released in Chronicle-Wire-1.12.7 (https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-1.12.7), BOM-1.15.310 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.310)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
