### ISSUE TITLE
commentListener is called multiple times when TextWire saves and reads unexpected fields

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Wire#866]
It seems that every time a field is run over, `commentListener` will trigger if field is unexpected.
This affects `TextWire` but `YamlWire` also needs checking.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.25ea13](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.25ea13), [BOM-2.25ea46](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25ea46)
