### ISSUE TITLE
Avro product comparison

### ISSUE THREAD

**Issue by EmmaChronicle** [OpenHFT/Chronicle-Wire#87]

**Comment by RobAustin** [comment]
let's consider this later.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.19.9](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.19.9), [BOM-2.19.111](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.111)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.19.9](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.19.9), [BOM-2.19.112](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.112)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.19.9](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.19.9), [BOM-2.19.116](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.116)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
