### ISSUE TITLE
JSONWire to parse doubles/ints surrounded by quotes

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Wire#886]
if a DTO has a double field "price" then parsing in this JSON results in price's value == -0.0
```
"price": "1.234"
```
If you take away the quotes it is parsed correctly as 1.234 e.g
```
"price": 1.234
```

**Comment by peter-lawrey** [comment]
Added double/float/long/int with single and double quote.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.25ea14](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.25ea14), [BOM-2.25ea52](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25ea52)
