### ISSUE TITLE
Anchor is ignored and alias is not found when dealing with text fields

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Wire#898]
Turns out there's pathway for Object but not for text.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.25.18](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.25.18), [BOM-2.25.68](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25.68)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.26ea1](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.26ea1), [BOM-2.26ea10](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.26ea10)
