### ISSUE TITLE
Chronicle-wire tagged 1.0.XX-beta pom.xml still references a ***-SNAPSHOT version of  Chronicle-bom

### ISSUE THREAD

**Issue by panterose** [OpenHFT/Chronicle-Wire#9]
Hi,
don't know if that's expected, but gradle complains when I add: compile 'net.openhft:chronicle-wire:1.+'. My graddle project as I rely only maven central repo, not your snapshot repo.
thanks,
B

**Comment by RobAustin** [comment]
yes, we was and issue with the last build, Im fixing it now, it should be in maven in a few hours

**Comment by peter-lawrey** [comment]
Assuming it is fix now.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
