### ISSUE TITLE
Improve copyTo for JSON <-> YAML, and handling of true/false values

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Wire#908]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.26ea2](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.26ea2), [BOM-2.26ea20](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.26ea20)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.25.23](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.25.23), [BOM-2.25.84](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25.84)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.25.23](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.25.23), [BOM-2.25.85](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25.85)
