### ISSUE TITLE
Create a common YAML ConfigLoader to use in leaf projects

### ISSUE THREAD

**Issue by david-ry4n** [OpenHFT/Chronicle-Wire#911]
Various sub-libraries and tests implement their own version of YAML base configuration loading. This is sometimes with and sometimes without property substitution. It would be useful to provide a common capabilities which can be used across libraries with the same implementation that includes ${property} style property substitution.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.26ea3](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.26ea3), [BOM-2.26ea21](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.26ea21)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.25.20](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.25.20), [BOM-2.25.74](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25.74)
