### ISSUE TITLE
WireMarshaller becomes recursive on self-referenced field

### ISSUE THREAD

**Issue by david-ry4n** [OpenHFT/Chronicle-Wire#915]
If a Class of X contains a field with a List\<X\> then WireMarshaller recursively attempts to resolve X.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.23.51](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.23.51), [BOM-2.23.220](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.220)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.24.31](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.24.31), [BOM-2.24.133](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24.133)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.26ea3](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.26ea3), [BOM-2.26ea21](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.26ea21)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.25.19](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.25.19), [BOM-2.25.72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25.72)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.25.19](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.25.19), [BOM-2.25.74](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25.74)
