### ISSUE TITLE
delta wire demo with queue

### ISSUE THREAD

**Issue by EmmaChronicle** [OpenHFT/Chronicle-Wire#92]

**Comment by RobAustin** [comment]
see https://github.com/ChronicleEnterprise/Chronicle-Queue-Enterprise-Demo/blob/master/docs/Example9-Wire-Enterprise.adoc

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
