### ISSUE TITLE
Fix: JsonWire fails to encode Unicode characters

### ISSUE THREAD

**Issue by maxim-ponomarev** [OpenHFT/Chronicle-Wire#934]
<img width="406" alt="Screenshot 2024-09-11 at 14 50 43" src="https://github.com/user-attachments/assets/227c4e65-1dd4-4b58-9d57-b53a84dc0fe9">

**Comment by tgd** [comment]
Awaiting review

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.27ea2](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.27ea2), [BOM-2.27ea11](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.27ea11)
