### ISSUE TITLE
JSONWire parser is confused when reading a field after null resolves to Double NaN

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Wire#953]
df307774 defines that NaN is turned into `null` on writing, and `null` is turned into NaN double on reading.
However, it seems that parsing such `null` sets parser in some bad state where it can no longer parse next fields in the same object.

I will attach a reproducer test.

**Comment by alamar** [comment]
Apparently, the situation is more severe: numbers parsing seems to depend on `BytesInternal.parseDouble()`s behavior to consume the next byte, expecting it to be a comma.
If it is not a comma (say, a whitespace), then JsonWire parsing of numbers runs into issues.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.27ea2](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.27ea2), [BOM-2.27ea11](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.27ea11)
