### ISSUE TITLE
Wire generates incorrect code when implementing Transport from Queue Web Gateway

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Wire#963]
When interface extends `Transport<T>` it has to redefine `T destination(...)` method explicitly, or method writer's generated code will not compile, and will not work correctly.

Workaround is known but the root case has to be addressed

**Comment by alamar** [comment]
Found one more edge case - reopening and will produce a fix.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.25.25](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.25.25), [BOM-2.25.94](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25.94)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.27ea1](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.27ea1), [BOM-2.27ea3](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.27ea3)
