### ISSUE TITLE
Relaxed the text yaml parser to accept common mistakes.

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Wire#97]
see example below
```
!software.chronicle.services.config.BadYamlParseTest$Dto {
  x:{ # sticky speaking this should contain a space between the : and the { 
    y: c
  },
  y: hello
}
```

**Comment by hft-team-city** [comment]
Released in [Chronicle-Wire-2.20.101](https://github.com/OpenHFT/Chronicle-Wire/releases/chronicle-wire-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
